### PR TITLE
Update .gitignore file

### PR DESCRIPTION
**Pull request by singhaditya28**
For better stability and security

### CODE REVIEW

**Comment by justinjhendrick** [comment]
Please direct general purpose pull requests to the upstream repository:  https://r8.googlesource.com/r8

**Comment by singhaditya28** [comment]
Sir don't you wish to develop something in the project by own.

**Comment by justinjhendrick** [comment]
Please see the README. I'll quote it here:

> This is a fork of the D8 dexer and R8 shrinker for use by Buck
>
> Please refer to the upstream repository: https://r8.googlesource.com/r8
>
> This fork isn’t intended to diverge greatly from D8/R8, it’s just a specialized version for people who use D8 within Buck (and possibly Redex after). This repository is not the source of truth.
>
> We will only consider PRs and issues related to D8/R8's integration with Buck and Redex in this repo. All other PRs and issues should be sent to https://r8.googlesource.com/r8

**Comment by singhaditya28** [comment]
Alright! @justinjhendrick . Thanks for your time and consideration. 👍 😃

**Pull request closed without merging**
